### PR TITLE
Matchers by domain

### PR DESCRIPTION
**Pull request by oxtoacart**
Here is a different approach. Basically, it still uses the adblock library matchers, however it organizes them into a prefix tree by domain. This does mean that rules which don't have a domain aren't matched, but rules that do have a domain are processed as usual.

Performance is also quite good:

```
10000000	       160 ns/op
```

### CODE REVIEW

**Comment by joesis** [comment]
Wow, another order of magnitude performance gain by using radix tree!

Unfortunately, `s3.amazonaws.com` or `nytimes.com` would sneak into the blocked domain list if only `DomainAnchor` is checked or the rules parts are checked like https://gist.github.com/oxtoacart/947d445d015f541d059ce3a72a812354#file-rules-go-L46. The `RuleOpts` needs to be checked too. That's why I think parsing text directly can be simpler.

Consider the traits of the list, I was working on breaking the rules into two parts: domain blocking for CONNECT requests and URL matching for HTTP requests. Using `go-radix` to match domains is a good optimization indeed, while `suffixarray` is good for URL matching as it requires regex.

**Comment by oxtoacart** [comment]
@joesis I'm not at a computer, but I think my code might be okay for what you want. It doesn't actually use the domains to filter, it still uses the matcher from the adblock library, it just segregates the matchers by domain for performance.

**Comment by joesis** [comment]
Oh, I see. Your method is definitely superior @oxtoacart!

Playing with the code to pass the test for `s3.amazonaws.com`. It seems more fields of `Request` needs to be filled.

**Comment by oxtoacart** [comment]
> Playing with the code to pass the test for s3.amazonaws.com. It seems more fields of Request needs to be filled.

Yes, I think you're right. I think we need `Referer -> OriginDomain` and `Content-Type->ContentType`.

**Comment by oxtoacart** [comment]
@joesis The problem with Amazon was due to a bug in the adblock library as you suspected. I've forked that library, fixed the bug and opened a [pr](https://github.com/pmezard/adblock/pull/1). For now, I'm pointing at our fork, which makes `easylist` work.

**Comment by joesis** [comment]
I cherry-picked the commit to avoid nil pointer when domain list is empty. 

LGTM @oxtoacart . The radix + adblock idea is neat!

**Comment by oxtoacart** [comment]
Thanks @joesis!

**Pull request merged**
