### PR TITLE
Properly parsing domains, closes getlantern/lantern-internal#777

### PR DESCRIPTION
**Pull request by oxtoacart**

### CODE REVIEW

**Comment by oxtoacart** [comment]
@myleshorton If you have time, you might be interested in this one too. @joesis caught this. Should be a quick review, and could explain the increased CPU usage that you observed sometimes.

**Comment by joesis** [comment]
This is LGTM. Actually I tried the same.

**Comment by oxtoacart** [comment]
Thanks for reviewing @joesis!

**Comment by myleshorton** [comment]
Wow good catch guys! Out of curiosity, how long does it take to initialize now? One thing that was pretty handy in the HTTPSEverywhere case was a preprocessing step that converted everything to Go's gob encoding before embedding it in via byteexec.

Oh, also I'm not sure if easylist uses matching groups, but I had to this to deal with Go's different use of matching groups:

https://github.com/getlantern/httpseverywhere/blob/master/deserializer.go#L111

Actually now that I'm looking at that I realize I should have done that in the initial serialization step! I'll fix that.

**Comment by myleshorton** [comment]
Oh I should note my code for swapping those matching groups is super crappy -- maybe I'll take the time to clean that up while I'm there!

**Comment by oxtoacart** [comment]
@myleshorton It initializes in about 1.2 seconds now. IIRC easylist doesn't even use regexes at all, but all that is handled by github.com/pmezard/adblock/adblock anyway.

**Comment by oxtoacart** [comment]
@myleshorton Out of curiosity, how much startup time does the GOB encoding save and how much space does it save (or add) vs just the text representation of the rules?

**Comment by myleshorton** [comment]
Oh OK cool that's interesting on the regexes @oxtoacart.

I'm not actually sure how much it saves on the space side. I largely did it to speed up the initial loading, which basically went from slowish (a couple seconds) to fast (about 250ms). I could do more rigorous tests if you like -- I didn't quantify it as much as I probably should have.

**Comment by oxtoacart** [comment]
> I could do more rigorous tests if you like -- I didn't quantify it as much as I probably should have.

Nah, I was just curious. It's working now, so I'd leave it.

**Comment by oxtoacart** [comment]
> I could do more rigorous tests if you like -- I didn't quantify it as much as I probably should have.

Nah, I was just curious. It's working now, so I'd leave it.

**Pull request merged**
